### ISSUE TITLE
PropType warning due to typo in code !

### ISSUE THREAD

**Issue by javierfernandes** [jeremy-carbonne/react-minimap#1]
Hi !

I'm getting this warning in the console when using minimap

```
Warning: Failed prop type: n: prop type `selector` is invalid; it must be a function, usually from React.PropTypes.
    in n (created by MiniMap)
    in MiniMap (created by TreeView)
```

I found that it is a typo in the proptype declaration
Here `selector: PropTypes.string.isRequied,`  an R is missing :P

**Comment by javierfernandes** [comment]
I've created a PR with a fix for this which also adds a test case.

Let me know if it is ok, then it would be great if you can deploy a new version with the fix :)

Thanks !

Cheers !

**Comment by jeremy-carbonne** [comment]
Thanks for the PR! I have publish a new version on npm.

**Comment by javierfernandes** [comment]
Thanks appreciated for your quick response !
