### ISSUE TITLE
Usage instructions not working

### ISSUE THREAD

**Issue by rajeshgoyalg** [jeremy-carbonne/react-minimap#11]
`import Minimap from 'react-minimap';
<Minimap selector=".card">
	<div className="card">
		<h1>Title</h1>
	</div>
	<div className="card">
		<h1>Title 2</h1>
		<div className="card">
			<h1>Titles are never rendered by the Minimap</h1>
		</div>
	</div>
</Minimap>`

**Comment by rajeshgoyalg** [comment]
I had to include CSS file and it display the minimap. Still dom elements does not reflect in the preview
`
import 'react-minimap/react-minimap.css';
`

**Comment by jeremy-carbonne** [comment]
You're right, I'll correct that
